cli: Fixes and refactoring for perf support
gimli-rs/addr2line pull request #244
Opened 2022-04-27 06:05 UTC by ishitatsuyuki

#### Background

The _perf_ utility uses either _libbfd_ or _addr2line_ to obtain information about inlined symbols (the record-time unwinding itself is handled by _libunwind_). Both option uses _libbfd_ under the hood, and it seems that _libbfd_ lacks the functionality of properly constructing a binary search index before doing the mass lookups. As a result, it runs like hot garbage for a lot of debug binaries.

The option to use an out-of-process _addr2line_ was originally added for Debian linking license reasons, but it turns out that with a little tweaking we can drop in a different addr2line implementation as well. With these modifications and Gimli's addr2line dropped into /usr/local/bin, `perf report` runs magnitudes faster (~100x? didn't measure) and there doesn't appear to be major issues.

**Important**: If you want to actually try, you need to (re)build perf with the `NO_LIBBFD` option passed to make. Probably only Debian has this by default.

#### Description

perf has a few assumptions about how addr2line behaves, and here we align two behavior differences with the GNU implementation:
1. We just give a "no match" when we can't parse the input address.
2. We output `??:0` instead of `??:?` for "no match".

There are also a few refactoring so that the output code can be streamlined.

2022-04-27 15:49 UTC, mstange commented
This sounds excellent!

Does `perf` use one long-running `addr2line` process these days, or does it relaunch `addr2line` for every address? If it relaunches for every address, then you're not benefiting from the addr2line-internal caching and could go even faster. (I saw [this post about using a long-running process](https://eighty-twenty.org/2021/09/09/perf-addr2line-speed-improvement) but I do not know whether this patch has made it into perf.)

2022-04-27 15:50 UTC, ishitatsuyuki commented
I’m running a build from 5.17 source tree and it’s using a persistent process.

2022-05-01 06:32 UTC, philipc requested changes
These changes are great. Please rebase onto `master` for CI.

2022-05-01 06:33 UTC, ishitatsuyuki commented
Rebased. Please approve CI as I'm a first-time contributor.

2022-05-01 06:55 UTC, philipc approved these changes

2022-05-01 06:57 UTC, merged