Grouped bar chart graph
gimli-rs/addr2line pull request #325
Opened 2024-08-05 05:18 UTC by marxin

The graph is based on the following example: https://matplotlib.org/stable/gallery/lines_bars_and_markers/barchart.html#sphx-glr-gallery-lines-bars-and-markers-barchart-py.

2024-08-05 07:19 UTC, philipc requested changes
Thanks, bars look much better.

2024-08-05 07:19 UTC, philipc commented on scripts/benchmark-plot.py
> +        )
Calculating the mean of a mean doesn't make sense to me, and nothing in this `for` loop needed to change anyway, so I prefer if you revert this block (the `sorted` above is fine). You'll need to add the `data = map(list, zip(*data))` back in below too.

2024-08-05 07:19 UTC, philipc commented on scripts/benchmark-plot.py
> +multiplier = 0
Use `enumerate` for the `for` loop instead of doing it manually.

2024-08-05 07:19 UTC, philipc commented on scripts/benchmark-plot.py
> +ax.legend(title="Tool")
This can be left how it was as `plt.legend` below, since it's unrelated to the x axis.

2024-08-05 07:19 UTC, philipc commented on scripts/benchmark-plot.py
> +ax.set_xticks(x + width, inputs)
This isn't centered. Maybe a calculation based on `len(commands)`? Hardcode would be fine too.

2024-08-05 07:24 UTC, philipc commented on scripts/benchmark-plot.py
> +        )
(`np.transpose(data)` is probably clearer than the map/zip.)

2024-08-05 09:38 UTC, marxin commented
I addressed all your comments, they were beneficial!

Note I also formatted the code with [`ruff` tool](https://docs.astral.sh/ruff/).

2024-08-06 01:38 UTC, philipc commented on scripts/benchmark-plot.py
> +    inputs.append(f"{input}\n({binary_size}, {symbol_queries} qrs)")
```suggestion
    inputs.append(f"{input}\n({binary_size}B,\n{symbol_queries} queries)")
```
"qrs" is a bit obscure.

2024-08-06 05:22 UTC, philipc approved these changes

2024-08-06 05:23 UTC, merged